---
- name: Clean persistent storage
  hosts: all
  become: yes

  vars:
    volume_path: "/var/lib/docker/volumes/myapp_storage_data/_data"
    storage_file: "/var/lib/docker/volumes/myapp_storage_data/_data/storage.txt"

  tasks:
    - name: Stop app containers
      command: docker compose -f /home/{{ ansible_user }}/myapp/docker-compose.yml down

    - name: Ensure volume directory exists
      file:
        path: "{{ volume_path }}"
        state: directory

    - name: Remove all files inside the volume
      file:
        path: "{{ volume_path }}"
        state: absent

    - name: Recreate volume directory
      file:
        path: "{{ volume_path }}"
        state: directory
        mode: '0755'

    - name: Create empty storage.txt
      file:
        path: "{{ storage_file }}"
        state: touch
        mode: '0644'

    - name: Restart app
      command: docker compose -f /home/{{ ansible_user }}/myapp/docker-compose.yml up -d
