---
- name: Deploy the application to remote host
  hosts: all
  become: yes

  vars:
    app_dir: "/home/{{ ansible_user }}/myapp"
    compose_file: "docker-compose.yml"

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker using official Docker repo
      shell: |
        set -e
        apt-get update
        apt-get install -y ca-certificates curl gnupg

        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc

        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
          > /etc/apt/sources.list.d/docker.list

        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      args:
        executable: /bin/bash

    - name: Ensure app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy application files
      synchronize:
        src: "./"
        dest: "{{ app_dir }}"
        delete: no
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.gitlab-ci.yml"
          - "--exclude=id_rsa"
          - "--exclude=__pycache__"
          - "--exclude=*.pyc"

    - name: Start application with Docker Compose
      command: docker compose -f {{ app_dir }}/{{ compose_file }} up -d --build
      args:
        chdir: "{{ app_dir }}"


